### ISSUE TITLE
0 vs O im Hash verhindern

### ISSUE THREAD

**Issue by dhavlik** [Eigenbaukombinat/ebk_coronalogin#1]

**Comment by Markus-Be** [comment]
Dann sollten wir auch gleich I und l mit verhindern

**Comment by dhavlik** [comment]
Und nur Kleinbuchstaben.
So geht das:
`hashids = Hashids(alphabet='abcdefghkmnpqrstuvwxyz')
`

**Comment by dhavlik** [comment]
erledigt
